name: Reusable Workflow User

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Enter Sprint branch'
        type: string
        required: true
jobs:
  call-workflow-passing-data:
    uses: Soorya8docker/ReusableWorkflow/.github/workflow/ReusableWorkflow.yml@main
    with:
      Branch: ${inputs.Branch}
